apiVersion: v1
kind: Pod
metadata:   # Who Am I
  name: podname
  labels:   # Tell to Others
    app: webappnameforotherservice
spec: # What I do
  containers: 
    - name: firstcontainer
      image: nginx
